// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var BsBox = require("../src/BsBox.bs.js");

var code = "\n  let hello thing =\n    Js.log {j|Hello $thing!|j}\n\n  let () =\n    hello (String.capitalize \"world\")\n";

var result = BsBox.compile(code);

if (result.tag) {
  console.log("Error: ", result[0][/* message */0]);
} else {
  var match = result[0];
  var warnings = match[/* warnings */1];
  var code$1 = match[/* code */0];
  if (warnings) {
    console.log("Warnings: ", warnings[0]);
  }
  console.log(code$1);
  eval(code$1);
}

exports.code   = code;
exports.result = result;
/* result Not a pure module */
