// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var BsBox = require("../src/BsBox.bs.js");

var code = "\n  let x =\n    match 0 with 0 -> ()\n";

var result = BsBox.compile(code);

if (result.tag) {
  console.log("Error: ", result[0][/* message */0]);
} else {
  var match = result[0];
  var warnings = match[/* warnings */1];
  if (warnings) {
    console.log("Warnings:\n", warnings[0]);
  }
  eval(match[/* code */0]);
}

exports.code   = code;
exports.result = result;
/* result Not a pure module */
